[package]
name = "rayt_rust"
version = "0.1.0"
authors = ["tekkoc <tekkoc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
minifb = "0.23.0"
rand = "0.8.5"
rayon = "1.5.3"
